### ISSUE TITLE
Call to undefined method DifferenceEngine::getOldRevision()

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticTasks#25]
### Setup and configuration

- SMW version: 3.1.0
- ST version: 2.0.0-alpha (4993064) 17:09, 17. Sep. 2019
- MW version: 1.31.4
- PHP version: 7.1.26 (fpm-fcgi)
- DB (MySQL etc. and version): MySQL | 5.5.62-cll

### Issue
```
 /index.php?title=60116_-_Projektbeginn&action=formedit Error from line 209 of /home/kdz/intern/extensions/SemanticTasks/src/SemanticTasksMailer.php: Call to undefined method DifferenceEngine::getOldRevision()
```
### Backtrace
```
#0. extensions/SemanticTasks/src/SemanticTasksMailer.php(159): ST\SemanticTasksMailer::generateDiffBodyTxt(Title)
#1. extensions/SemanticTasks/src/SemanticTasksMailer.php(119): ST\SemanticTasksMailer::mailNotification(array, string, Title, User, integer)
#2 extensions/SemanticTasks/src/SemanticTasksMailer.php(65): ST\SemanticTasksMailer::mailAssignees(WikiPage, WikitextContent, User, integer, ST\Assignees)
#3 extensions/SemanticTasks/SemanticTasks.php(74): ST\SemanticTasksMailer::mailAssigneesUpdatedTask(ST\Assignees, WikiPage, User, WikitextContent, string, integer, NULL, NULL, integer)
#4 /includes/Hooks.php(177): SemanticTasks::{closure}(WikiPage, User, WikitextContent, string, integer, NULL, NULL, integer, Revision, Status, boolean, integer)
#5 /includes/Hooks.php(205): Hooks::callHook(string, array, array, NULL)
#6 /includes/page/WikiPage.php(1853): Hooks::run(string, array)
#7 [internal function]: WikiPage->{closure}(Wikimedia\Rdbms\DatabaseMysqli, string)
#8 /includes/libs/rdbms/database/Database.php(3664): call_user_func_array(Closure, array)
#9 /includes/deferred/AtomicSectionUpdate.php(35): Wikimedia\Rdbms\Database->doAtomicSection(string, Closure)
#10 /includes/deferred/DeferredUpdates.php(259): AtomicSectionUpdate->doUpdate()
#11 /home/kdz/intern/includes/deferred/DeferredUpdates.php(210): DeferredUpdates::runUpdate(AtomicSectionUpdate, Wikimedia\Rdbms\LBFactorySimple, string, integer)
#12 /includes/deferred/DeferredUpdates.php(127): DeferredUpdates::execute(array, string, integer)
#13 /includes/MediaWiki.php(606): DeferredUpdates::doUpdates(string, integer)
#14 /includes/MediaWiki.php(575): MediaWiki::preOutputCommit(RequestContext, Closure)
#15 /includes/MediaWiki.php(877): MediaWiki->doPreOutputCommit(Closure)
#16 /includes/MediaWiki.php(524): MediaWiki->main()
#17 /index.php(42): MediaWiki->run()
#18 {main}
```
### Steps to reproduce
1. Create a new page with property "Assigned to" some User. No E-Mail is sent.
2. Other user edits the page. The error is displayed, however the changes in the page are saved. No E-Mail is sent.

**Comment by krabina** [comment]
No, it does not:
```
[XcQtRydC3RHVhesaAOUTRQAAABM] /index.php?title=Gewerbeanmeldung&action=formedit Error from line 209 of ../extensions/SemanticTasks/src/SemanticTasksMailer.php: Call to undefined method DifferenceEngine::getOldRevision()

Backtrace:

#0 ../extensions/SemanticTasks/src/SemanticTasksMailer.php(159): ST\SemanticTasksMailer::generateDiffBodyTxt(Title)
#1 ../extensions/SemanticTasks/src/SemanticTasksMailer.php(119): ST\SemanticTasksMailer::mailNotification(array, string, Title, User, integer)
#2 ../extensions/SemanticTasks/src/SemanticTasksMailer.php(65): ST\SemanticTasksMailer::mailAssignees(WikiPage, WikitextContent, User, integer, ST\Assignees)
#3 ../extensions/SemanticTasks/SemanticTasks.php(80): ST\SemanticTasksMailer::mailAssigneesUpdatedTask(ST\Assignees, WikiPage, User, WikitextContent, string, integer, NULL, NULL, integer)
#4 ../includes/Hooks.php(177): SemanticTasks::{closure}(WikiPage, User, WikitextContent, string, integer, NULL, NULL, integer, Revision, Status, boolean, integer)
#5 ../includes/Hooks.php(205): Hooks::callHook(string, array, array, NULL)
#6 ../includes/page/WikiPage.php(1853): Hooks::run(string, array)
#7 [internal function]: WikiPage->{closure}(Wikimedia\Rdbms\DatabaseMysqli, string)
#8 ../includes/libs/rdbms/database/Database.php(3664): call_user_func_array(Closure, array)
#9 ../includes/deferred/AtomicSectionUpdate.php(35): Wikimedia\Rdbms\Database->doAtomicSection(string, Closure)
#10 ../includes/deferred/DeferredUpdates.php(259): AtomicSectionUpdate->doUpdate()
#11 ../includes/deferred/DeferredUpdates.php(210): DeferredUpdates::runUpdate(AtomicSectionUpdate, Wikimedia\Rdbms\LBFactorySimple, string, integer)
#12 ../includes/deferred/DeferredUpdates.php(127): DeferredUpdates::execute(array, string, integer)
#13 ../includes/MediaWiki.php(606): DeferredUpdates::doUpdates(string, integer)
#14 ../includes/MediaWiki.php(575): MediaWiki::preOutputCommit(RequestContext, Closure)
#15 ../includes/MediaWiki.php(877): MediaWiki->doPreOutputCommit(Closure)
#16 ../includes/MediaWiki.php(524): MediaWiki->main()
#17 ../index.php(42): MediaWiki->run()
#18 {main}
```

**Comment by krabina** [comment]
btw; I just figured that the error only shows up in SMW 3.1.0. In an installation with SMW 3.0.2 it does not show!

**Comment by PeterTheOne** [comment]
Did you use the code from the PR? the error is in the same line but the lines changed.. Anyway, I will do some more debugging then.

**Comment by PeterTheOne** [comment]
I've tested generateDiffBodyTxt() now in #27, seems to work in:

- DB=sqlite; MW=REL1_31; SMW=~3.0;
- DB=sqlite; MW=REL1_31; SMW=~3.0@dev
- DB=postgres; MW=REL1_33; SMW=~3.0@dev; TYPE=coverage PHP: 7.2

**Comment by krabina** [comment]
I can confirm that with 2.0.0-alpha (62a5ef2) the error goes away and the extension seems to work fine. 
My remaining problem is #15
